version: '3.3'
services:
  db:
    container_name: kyouka_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kyouka_db
    ports:
      - '5432:5432'