export const images = {
    cryCommand: [
        'https://i.imgur.com/MieyWrt.gif',
        'https://i.imgur.com/DHawcrE.gif',
        'https://i.imgur.com/OB50VDV.gif',
        'https://i.imgur.com/EyT3wYS.gif',
        'https://i.imgur.com/3Dyo0RH.gif',
        'https://i.imgur.com/vKB9C5j.gif',
        'https://i.imgur.com/EuoGFE2.gif',
        'https://i.imgur.com/BDOfmSO.gif',
        'https://i.imgur.com/0njPbV3.gif',
        'https://i.imgur.com/aNj3mv7.gif',
        'https://i.imgur.com/piQ9Yb0.gif',
        'https://i.imgur.com/ZMiEvse.gif',
        'https://i.imgur.com/qqRGzE3.gif',
        'https://i.imgur.com/W9yHs4t.gif',
        'https://i.imgur.com/U83C71w.gif',
        'https://i.imgur.com/4W0wCGd.gif',
        'https://i.imgur.com/f0NP6vY.gif',
        'https://i.imgur.com/sbVIswx.gif',
    ],
};
